# Generated by Django 4.2.5 on 2023-10-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="followers",
            name="user_id",
        ),
        migrations.AddField(
            model_name="followers",
            name="user",
            field=models.CharField(default="null"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="page",
            name="user",
            field=models.CharField(),
        ),
    ]
