# Generated by Django 4.2.5 on 2023-10-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_alter_post_reply_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="likes",
            name="user_id",
        ),
        migrations.AddField(
            model_name="likes",
            name="user",
            field=models.CharField(default="unknown"),
            preserve_default=False,
        ),
    ]
