# Generated by Django 4.2.5 on 2023-10-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_remove_post_likes_post_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="likes", to="post.likes"
            ),
        ),
    ]
