# Generated by Django 4.2.5 on 2023-10-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_remove_post_likes_post_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(blank=True, to="post.likes"),
        ),
    ]
