# Generated by Django 4.2.5 on 2023-10-10 13:50

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_alter_post_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="likes",
            name="user",
        ),
        migrations.AddField(
            model_name="likes",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
